version: '2.2'
networks:
    mynetwork:

services:
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
        networks:
            - mynetwork
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.11.2
        networks:
            - mynetwork
        links: 
            - elasticsearch:elasticsearch
        ports:
            - 5601:5601
    
    nginx:
      container_name: nginx
      image: nginx
      networks:
        - mynetwork
      ports:
        - 80:80
      volumes:
        - nginx.conf:/etc/nginx/nginx.conf